# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from decimal import Decimal

from config import MIN_PRECISION_BTC


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 241, 121))
        self.label.setStyleSheet("font: 30pt \"Adobe Arabic\";\nborder: 10px double #242424;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 91, 61))
        self.label_2.setStyleSheet("font: 24pt \"Adobe Arabic\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_balance = QtWidgets.QLabel(self.centralwidget)
        self.label_balance.setGeometry(QtCore.QRect(120, 150, 111, 61))
        self.label_balance.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.label_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_balance.setObjectName("label_balance")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 241, 61))
        self.label_4.setStyleSheet("border: 3px solid #242424;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 20, 281, 121))
        self.label_5.setStyleSheet("font: 30pt \"Adobe Arabic\";\nborder: 10px double #242424;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 160, 281, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.box_pay_btcs = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.box_pay_btcs.setDecimals(MIN_PRECISION_BTC)
        self.box_pay_btcs.setMinimum(Decimal("0.1")**MIN_PRECISION_BTC)
        self.box_pay_btcs.setMaximum(200.0)
        self.box_pay_btcs.setObjectName("box_pay_btcs")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_pay_btcs)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.line_pay_address = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_pay_address.setText("")
        self.line_pay_address.setMaxLength(64)
        self.line_pay_address.setObjectName("line_pay_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_pay_address)
        self.verticalLayout.addLayout(self.formLayout)
        self.btn_add_output = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_output.setObjectName("btn_add_output")
        self.verticalLayout.addWidget(self.btn_add_output)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.edit_trans = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.edit_trans.setObjectName("edit_trans")
        self.verticalLayout.addWidget(self.edit_trans)
        self.btn_broad_trans = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_broad_trans.setObjectName("btn_broad_trans")
        self.verticalLayout.addWidget(self.btn_broad_trans)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 241, 91))
        self.label_10.setStyleSheet("font: 30pt \"Adobe Arabic\";\nborder: 10px double #242424;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btn_mining = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mining.setGeometry(QtCore.QRect(20, 430, 221, 41))
        self.btn_mining.setStyleSheet("font: 15pt \"Adobe Arabic\";")
        self.btn_mining.setObjectName("btn_mining")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(270, 10, 20, 461))
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 260, 261, 20))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_export_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export_key.setGeometry(QtCore.QRect(10, 220, 111, 31))
        self.btn_export_key.setObjectName("btn_export_key")
        self.btn_import_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import_key.setGeometry(QtCore.QRect(140, 220, 111, 31))
        self.btn_import_key.setObjectName("btn_import_key")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 390, 161, 31))
        self.label_3.setStyleSheet("font: 12pt \"仿宋\";\nborder: 3px solid #242424;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_block_height = QtWidgets.QLabel(self.centralwidget)
        self.label_block_height.setGeometry(QtCore.QRect(170, 390, 81, 31))
        self.label_block_height.setStyleSheet("font: 15pt \"Times New Roman\";\nborder: 3px solid #242424;")
        self.label_block_height.setAlignment(QtCore.Qt.AlignCenter)
        self.label_block_height.setObjectName("label_block_height")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_balance.raise_()
        self.label_5.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_10.raise_()
        self.btn_mining.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.btn_export_key.raise_()
        self.btn_import_key.raise_()
        self.label_3.raise_()
        self.label_block_height.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "余   额"))
        self.label_2.setText(_translate("MainWindow", "Btcs："))
        self.label_balance.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "付   钱"))
        self.label_6.setText(_translate("MainWindow", "btcs："))
        self.label_7.setText(_translate("MainWindow", "address："))
        self.btn_add_output.setText(_translate("MainWindow", "添加输出"))
        self.label_8.setText(_translate("MainWindow", "生成交易："))
        self.btn_broad_trans.setText(_translate("MainWindow", "广播交易"))
        self.label_10.setText(_translate("MainWindow", "挖   矿"))
        self.btn_mining.setText(_translate("MainWindow", "开始挖矿"))
        self.btn_export_key.setText(_translate("MainWindow", "导出密钥"))
        self.btn_import_key.setText(_translate("MainWindow", "导入密钥"))
        self.label_3.setText(_translate("MainWindow", "当前区块高度："))
        self.label_block_height.setText(_translate("MainWindow", "0"))
